# Generated by Django 3.2.25 on 2024-09-11 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Transistor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=10, unique=True, verbose_name='наименование')),
                ('type', models.CharField(choices=[('TBN', 'Биполярный NPN'), ('TBP', 'Биполярный PNP'), ('TPN', 'Полевой N-канал'), ('TPP', 'Полевой P-канал'), ('OPT', 'Однопереходной'), ('NGB', 'Транзистор NGBT')], max_length=3, verbose_name='тип транзистора')),
                ('korpus', models.CharField(choices=[('TO-92', 'TO-92'), ('SOT-23', 'SOT-23'), ('SOT-89', 'SOT-89'), ('SOT-223', 'SOT-223'), ('TO-126', 'TO-126'), ('TO-220', 'TO-220'), ('TO-252', 'TO-252'), ('SOT-669', 'SOT-669'), ('TO-263', 'TO-263')], default='TO-92', max_length=20, verbose_name='тип корпуса')),
                ('descr', models.TextField(blank=True, verbose_name='краткое описание')),
                ('amount', models.IntegerField(blank=True, default=0, verbose_name='количество, шт.')),
                ('path_file', models.FileField(blank=True, default=None, upload_to='datasheet/transistors', verbose_name='datasheet/')),
            ],
        ),
    ]
