# Generated by Django 3.2.25 on 2024-09-11 11:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TypeTransistor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_tr', models.CharField(db_index=True, max_length=20, unique=True, verbose_name='тип_транзистора')),
            ],
        ),
        migrations.AlterField(
            model_name='transistor',
            name='path_file',
            field=models.FileField(blank=True, default=None, upload_to='datasheet/transistors', verbose_name='datasheet'),
        ),
        migrations.AlterField(
            model_name='transistor',
            name='type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='app.typetransistor'),
        ),
    ]
