# Generated by Django 4.1.3 on 2024-09-08 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='transistor',
            name='descr',
            field=models.TextField(default='Описание'),
        ),
    ]
