# Generated by Django 4.2.11 on 2024-09-10 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transistor',
            name='path_file',
            field=models.FileField(upload_to='datasheet'),
        ),
    ]
