# Generated by Django 4.2.11 on 2024-09-10 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_transistor_path_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transistor',
            name='path_file',
            field=models.FileField(blank=True, default=None, upload_to='datasheet', verbose_name='DataSheet'),
        ),
    ]
