# Generated by Django 3.2.25 on 2024-09-11 11:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20240911_1104'),
    ]

    operations = [
        migrations.CreateModel(
            name='KorpusTransistor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('korpus_tr', models.CharField(db_index=True, max_length=8, unique=True, verbose_name='тип_корпуса')),
            ],
        ),
        migrations.AlterField(
            model_name='transistor',
            name='type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='app.typetransistor', verbose_name='тип транзистора'),
        ),
        migrations.AlterField(
            model_name='transistor',
            name='korpus',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='app.korpustransistor', verbose_name='корпус'),
        ),
    ]
