# Generated by Django 4.1.3 on 2024-09-08 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_transistor_descr'),
    ]

    operations = [
        migrations.AddField(
            model_name='transistor',
            name='amount',
            field=models.IntegerField(default=0, max_length=10),
        ),
    ]
