# Generated by Django 3.2.25 on 2024-09-11 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20240911_1130'),
    ]

    operations = [
        migrations.AddField(
            model_name='transistor',
            name='markname',
            field=models.CharField(blank=True, max_length=20, verbose_name='маркировка'),
        ),
    ]
