# Generated by Django 4.2.11 on 2024-09-10 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_transistor_path_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transistor',
            name='amount',
            field=models.IntegerField(blank=True, default=0, verbose_name='количество, шт.'),
        ),
        migrations.AlterField(
            model_name='transistor',
            name='descr',
            field=models.TextField(blank=True, verbose_name='краткое описание'),
        ),
        migrations.AlterField(
            model_name='transistor',
            name='korpus',
            field=models.CharField(choices=[('TO-92', 'TO-92'), ('SOT-23', 'SOT-23'), ('SOT-89', 'SOT-89'), ('SOT-223', 'SOT-223'), ('TO-126', 'TO-126'), ('TO-220', 'TO-220'), ('TO-252', 'TO-252'), ('SOT-669', 'SOT-669'), ('TO-263', 'TO-263')], default='TO-92', max_length=20, verbose_name='тип корпуса'),
        ),
        migrations.AlterField(
            model_name='transistor',
            name='name',
            field=models.CharField(db_index=True, max_length=10, unique=True, verbose_name='наименование'),
        ),
        migrations.AlterField(
            model_name='transistor',
            name='path_file',
            field=models.FileField(blank=True, default=None, upload_to='datasheet', verbose_name='datasheet'),
        ),
        migrations.AlterField(
            model_name='transistor',
            name='type',
            field=models.CharField(choices=[('TBN', 'Биполярный NPN'), ('TBP', 'Биполярный PNP'), ('TPN', 'Полевой N-канал'), ('TPP', 'Полевой P-канал'), ('OPT', 'Однопереходной'), ('NGB', 'Транзистор NGBT')], max_length=3, verbose_name='тип транзистора'),
        ),
    ]
