# Generated by Django 4.2.11 on 2024-09-10 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_alter_transistor_path_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transistor',
            name='amount',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='transistor',
            name='korpus',
            field=models.CharField(choices=[('TO-92', 'TO-92'), ('SOT-23', 'SOT-23'), ('SOT-89', 'SOT-89'), ('SOT-223', 'SOT-223'), ('TO-126', 'TO-126'), ('TO-220', 'TO-220'), ('TO-252', 'TO-252'), ('SOT-669', 'SOT-669'), ('TO-263', 'TO-263')], default='TO-92', max_length=8),
        ),
        migrations.AlterField(
            model_name='transistor',
            name='path_file',
            field=models.FileField(upload_to='static/files/'),
        ),
    ]
