# Generated by Django 3.2.25 on 2024-09-12 10:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0005_transistor_userid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transistor',
            name='userid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth.user', verbose_name='user'),
        ),
    ]
