# Generated by Django 3.2.25 on 2024-09-10 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_alter_transistor_korpus'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transistor',
            name='path_file',
            field=models.FileField(upload_to='app/files'),
        ),
    ]
