# Generated by Django 3.2.25 on 2024-09-10 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_alter_transistor_path_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transistor',
            name='amount',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='transistor',
            name='path_file',
            field=models.FileField(null=True, upload_to='files/'),
        ),
    ]
