# Generated by Django 4.2.11 on 2024-09-12 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_alter_transistor_userid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transistor',
            name='name',
            field=models.CharField(db_index=True, max_length=10, verbose_name='наименование'),
        ),
    ]
